name: Run KoboData Script

on:
  schedule:
    # Ejecutar a las 4:00 y 16:00 hora Colombia (UTC-5)
    - cron: "0 9,21 * * *"

  workflow_dispatch:  # Permite ejecutarlo manualmente
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests gspread google-auth openpyxl

    - name: Add Google credentials
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

    - name: Run script
      run: python KoboData_2RepInfCampo.py
