name: Run Kobo Report Twice Daily

on:
  schedule:
    - cron: "0 9,21 * * *"   # 4 AM y 4 PM hora Colombia (09:00 y 21:00 UTC)
  workflow_dispatch:          # Permite ejecutarlo manualmente también

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          KOBO_TOKEN: ${{ secrets.KOBO_TOKEN }}
        run: python KoboData_2RepInfCampo.py

      - name: Upload output folder (overwrite)
        uses: actions/upload-artifact@v4
        with:
          name: ReporteInfCampo
          path: output/
          overwrite: true
