name: Run Kobo Report Daily

on:
  schedule:
    - cron: "0 17 * * *"   # Ejecuta todos los días a las 17:00 UTC (12:00 M Colombia)
  workflow_dispatch:        # Permite ejecutarlo manualmente también

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          KOBO_TOKEN: ${{ secrets.KOBO_TOKEN }}   # Solo se usa si la API es privada
        run: python script.py

      - name: Upload Excel
        uses: actions/upload-artifact@v3
        with:
          name: ReporteInfCampo
          path: output/2_ReporteInfCampo.xlsx
